//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollProject
{
    using System;
    
    public partial class GetEmployeePayments_Result2
    {
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal PaymentAmount { get; set; }
        public Nullable<System.DateTime> Pay_Date { get; set; }
        public int PaymentID { get; set; }
    }
}
