//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public int EmployeeID { get; set; }
        public decimal PaymentAmount { get; set; }
        public System.DateTime PAYDATE { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
